---
title: "Geocode french EUTL data with postal codes"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(here)
library(parallel)
library(sf)
```

```{r}
data_dir <- here('raw_data')
```


```{r prepare-postal-codes}
# Base SIRENE
# https://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/
sirene_url = "https://files.data.gouv.fr/insee-sirene/StockEtablissement_utf8.zip"
sirene_destfile <-  str_c(data_dir, "/etablissements-sirene.zip")
if (!file.exists(sirene_destfile)) {
  download.file(sirene_url, sirene_destfile)
  # The unzipped CSV file is more than 4GB, so R's unzip will choke on it
  # We've got to unzip it manually
  unzip(sirene_destfile,
        unzip = getOption("unzip"),
        exdir = data_dir)
}
sirene_csv <-
  str_c(data_dir, '/', unzip(sirene_destfile, list = TRUE)[[1]])

# Base des codes postaux
# https://www.data.gouv.fr/fr/datasets/base-officielle-des-codes-postaux/
postcodes_url <-
  "https://datanova.legroupe.laposte.fr/explore/dataset/laposte_hexasmal/download/?format=csv&timezone=Europe/Berlin&use_labels_for_header=true"
postcodes_csv <- str_c(data_dir, "/code_postaux.csv")
if (!file.exists(postcodes_csv)) {
  download.file(postcodes_url, postcodes_csv)
}

base_sirene <- read_csv(
  sirene_csv,
  col_types = cols_only(
    codePostalEtablissement = col_character(),
    codeCedexEtablissement = col_character()
  )
)

base_cedex <- base_sirene %>%
  filter(!is.na(codeCedexEtablissement) &
           !is.na(codePostalEtablissement)) %>%
  distinct(codeCedexEtablissement, .keep_all = TRUE) %>%
  rename(cp = codePostalEtablissement,
         cedex = codeCedexEtablissement)

base_postalcode <-  read_delim(postcodes_csv,
                               delim = ";",
                               col_types = "cccccc") %>%
  rename_with(tolower) %>%
  select(code_postal, coordonnees_gps) %>%
  distinct(code_postal, .keep_all = TRUE) %>%
  separate(coordonnees_gps,
           into = c("latitude", "longitude"),
           sep = ",")

base_cedex_geo <- base_cedex %>%
  left_join(base_postalcode, by = c("cp" = "code_postal")) %>%
  select(-cp) %>%
  rename(code_postal = cedex)

full_base_postalcode <- base_cedex_geo %>%
  rbind(base_postalcode) %>%
  distinct(code_postal, .keep_all = TRUE)
```

### France only

```{r manual-fix-cp}

installations_fr <- read_csv(here('export/installations-fr.csv')) 

unknown_cps <- installations_fr %>%
  anti_join(full_base_postalcode, by = c("ZipCode" = "code_postal")) %>% 
  distinct(ZipCode, .keep_all = TRUE) %>%
  arrange(by = ZipCode)
print(unknown_cps$ZipCode )


installations_fr[installations_fr$ZipCode == "10402", 'ZipCode'] <- "10400"
installations_fr[installations_fr$ZipCode == "13165", 'ZipCode'] <- "13220"
installations_fr[installations_fr$ZipCode == "29224", 'ZipCode'] <- "29460"
installations_fr[installations_fr$ZipCode == "31401", 'ZipCode'] <- "31000"
installations_fr[installations_fr$ZipCode == "38129", 'ZipCode'] <- "38500"
installations_fr[installations_fr$ZipCode == "38148", 'ZipCode'] <- "38140"
installations_fr[installations_fr$ZipCode == "38556", 'ZipCode'] <- "38550"
installations_fr[installations_fr$ZipCode == "42803", 'ZipCode'] <- "42800"
installations_fr[installations_fr$ZipCode == "46131", 'ZipCode'] <- "46130"
installations_fr[installations_fr$ZipCode == "50444", 'ZipCode'] <- "50440"
installations_fr[installations_fr$ZipCode == "54212", 'ZipCode'] <- "54200"
installations_fr[installations_fr$ZipCode == "60435", 'ZipCode'] <- "60430"
installations_fr[installations_fr$ZipCode == "60544", 'ZipCode'] <- "60110"
installations_fr[installations_fr$ZipCode == "60871", 'ZipCode'] <- "60870"
installations_fr[installations_fr$ZipCode == "62193", 'ZipCode'] <- "62190"
installations_fr[installations_fr$ZipCode == "65309", 'ZipCode'] <- "65300"
installations_fr[installations_fr$ZipCode == "68331", 'ZipCode'] <- "68330"
installations_fr[installations_fr$ZipCode == "69583", 'ZipCode'] <- "69250"
installations_fr[installations_fr$ZipCode == "71014", 'ZipCode'] <- "71000"
installations_fr[installations_fr$ZipCode == "72086", 'ZipCode'] <- "72000"
installations_fr[installations_fr$ZipCode == "73403", 'ZipCode'] <- "73400"
installations_fr[installations_fr$ZipCode == "74961", 'ZipCode'] <- "74960"
installations_fr[installations_fr$ZipCode == "76808", 'ZipCode'] <- "76800"
installations_fr[installations_fr$ZipCode == "77291", 'ZipCode'] <- "77990"
installations_fr[installations_fr$ZipCode == "87206", 'ZipCode'] <- "87200"
installations_fr[installations_fr$ZipCode == "88155", 'ZipCode'] <- "88150"
installations_fr[installations_fr$ZipCode == "91895", 'ZipCode'] <- "91400"
installations_fr[installations_fr$ZipCode == "97242", 'ZipCode'] <- "97200"
installations_fr[installations_fr$ZipCode == "97292", 'ZipCode'] <- "97232"
installations_fr[installations_fr$ZipCode == "97610", 'ZipCode'] <- "97615"
installations_fr[installations_fr$ZipCode == "97690", 'ZipCode'] <- "97600"

full_base_postalcode[full_base_postalcode$code_postal == "97133", 'latitude'] =  "17,9"
full_base_postalcode[full_base_postalcode$code_postal == "97133", 'longitude'] =  "-62,8333"
full_base_postalcode[full_base_postalcode$code_postal == "97150", 'latitude'] =  "18.073099"
full_base_postalcode[full_base_postalcode$code_postal == "97150", 'longitude'] = "-63.082199"
full_base_postalcode[full_base_postalcode$code_postal == "97500", 'latitude'] = "47.1002"
full_base_postalcode[full_base_postalcode$code_postal == "97500", 'longitude'] = "-56.3812"
```


```{r geolocalize-by-cp}

fr_emitters_geo <- installations_fr %>%
  left_join(full_base_postalcode, by = c("ZipCode" = "code_postal")) %>%
  distinct(InstallationOrAircraftOperatorID, .keep_all = TRUE) %>%
  filter(!is.na(latitude) & !is.na(longitude)) 
  

fr_emissions <- st_as_sf(fr_emitters_geo,
               coords = c('longitude', 'latitude'),
               na.fail = FALSE) %>% 
  st_set_crs(4326)

st_write(fr_emissions, here("out/fr_emissions.geojson"), append = FALSE, delete_dsn = TRUE)
st_write(fr_emissions, here("out/fr_emissions.gpkg"), append = FALSE, delete_dsn = TRUE)
st_write(fr_emissions, here("out/fr_emissions.csv"), append = FALSE, delete_dsn = TRUE, layer_options = "GEOMETRY=AS_XY")
```


